### ISSUE TITLE
Error when importing an Xpansion study with existing sensitivity directory

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1203]
When I import an Xpansion study such that it already has a folder `user/expansion/sensitivity`, I get an error when I try to get into the Xpansion tab of the study with the following message : 

Échec du chargement de la configuration d'Xpansion
Status : 500
Exception : ValidationError
Description : Unexpected server error

AxiosError: Request failed with status code 500

Whenever I remove the sensitivity folder, the error disappears and I can get to the Xpansion tab normally.

[An example study](https://antares-web-recette.rte-france.com/studies/a9af2043-311d-466e-975e-5eb822c4b76f)

**Comment by laurent-laporte-pro** [comment]
Traceback:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/ratelimit/core.py", line 82, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/antarest/core/logging/utils.py", line 104, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/antarest/core/utils/fastapi_sqlalchemy/middleware.py", line 56, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/antarest/study/web/xpansion_studies_blueprint.py", line 90, in get_settings
    return study_service.get_xpansion_settings(uuid=uuid, params=params)
  File "/antarest/study/service.py", line 2162, in get_xpansion_settings
    return self.xpansion_manager.get_xpansion_settings(study)
  File "/antarest/study/business/xpansion_management.py", line 302, in get_xpansion_settings
    return XpansionSettingsDTO.parse_obj(json)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for XpansionSettingsDTO
sensitivity_config -> projection
  field required (type=value_error.missing)
```

**Comment by MartinBelthle** [comment]
How to test the new behavior:

1. Create a study with an Xpansion configuration
2. Import a json to user/expansion/sensitivity/sensitivity_in (you can do it with the raw api) with missing "projection" key, example: {"epsilon": 14.5, "capex":False}
3. Go back to the xpansion screen
4. Old behavior: "AxiosError: Request failed with status code 500" screen. New behavior, normal screen
