### ISSUE TITLE
Avoid duplicate output_id when launching study

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1309]
## Description

When running several simulations of the same study in a very short time interval (less than 1 minute), the outputs can have the same name. In this case, the `output_id` value which is used to identify an output directory is the same because it is calculated according to the date and time of the end of calculation of a study (to the second).

### Steps to reproduce the behaviour:

1. Open a study in the webapp
2. Click on "Launch" button several times in a short time interval

## Actual Behaviour

You can see the launch of the studies in the task manager.

When the calculation is finished, one task will have succeeded while the others will fail when retrieving the result (`output`).
The failing studies have the same date and time (to the second).
We can see the message "Unexpected error when importing study output" in the task logs.

## Expected Behaviour

All simulations should succeed.

## Screenshots

![issue-1309](https://user-images.githubusercontent.com/43534797/218690754-a401b3cc-4af2-41b1-9603-945991e9a72f.png)

## Possible Solution

Workaround:

- use a small time duration between two study launching.
- or, use the `name` optional parameter to name your output differently for each launching.

## Environment

- [x] Production
- [x] Staging

### Add any other context about the problem here.

- Example of study: `a2236dd5-db12-4b2a-a009-a96925c4405c`

**Comment by laurent-laporte-pro** [comment]
We have the following error message in the logs:

```python

Unexpected error when importing study output : (<HTTPStatus.BAD_REQUEST: 400>, 'Study output is already (un)archiving'
```

**Comment by laurent-laporte-pro** [comment]
| **NOTE:** Nous n'avons plus l'erreur précédente "Unexpected error when importing study output ..."

Lorsque la même simulation d'étude est exécutée plusieurs fois avec des intervalles de temps courts (par exemple < 10s), nous avons une exception indiquant que la tâche est déjà en cours d'exécution.

Exemple avec l'étude `b13df377-9121-4c72-9fdc-a6cd74c4696a` et la tâche `11f9a766-ff34-4c3e-8348-2d35ba002394` :

```python
An error occurred unexpectedly while importing the study output: study.name='11f9a766-ff34-4c3e-8348-2d35ba002394', study.xpansion_mode=None, study.job_log_dir='/slurm_workspace/LOGS/JOB_LOGS/11f9a766-ff34-4c3e-8348-2d35ba002394_15772', see stack trace below:
Traceback (most recent call last):
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 431, in _handle_success
    output_id = self._import_study_output(
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 280, in _import_study_output
    return self.callbacks.import_output(
  File "/antarest/launcher/service.py", line 618, in _import_output
    return self.study_service.import_output(
  File "/antarest/study/service.py", line 1553, in import_output
    self.unarchive_output(
  File "/antarest/study/service.py", line 2467, in unarchive_output
    raise TaskAlreadyRunning()
antarest.core.exceptions.TaskAlreadyRunning
```

Il y a une anomalie au niveau d'AntaREST mais pas au niveau d'Antares Launcher car on observe bien que tous les fichiers ont été récupérés.

**Comment by laurent-laporte-pro** [comment]
@MartinBelthle Il faudrait statuer sur cette anomalie afin de savoir si elle est encore d'actualité. Sinon, un complément d'information est nécessaire. Pourrais-tu refaire des tests à ce sujet ?

**Comment by MartinBelthle** [comment]
J'ai testé sur integration (Antares Web 2.13.2) et aucun lancement n'a fail. Par contre, il y a toujours unicité des outputs qui finissent au même moment avec le même nom.
