### ISSUE TITLE
FileNotFound exception raised when a simulation fails

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1379]
## Description

Lorsqu'une simulation exécutée sur Antares Simulateur échoue (quelle qu'en soit la raison), un message d'exception est affiché, car Antares Web cherche à récupérer le répertoire `output`, or, dans le cas d'un échec, ce répertoire n'existe pas toujours.

Le message d'erreur `FileNotFoundError`, même s'il est pertinent, masque le réel problème qui est un plantage de la simulation.

## Étapes pour reproduire le comportement :

1. Lancer une simulation avec une étude vide (sans zone) afin de provoquer une erreur côté simulation

## Comportement actuel

L'exécution se termine bien en erreur. Dans le liste des tâches, on trouve les deux logs:

- Dans les logs, on a l'erreur `FileNotFoundError` 
- Le fichier de log d'erreur, on a bien l'erreur de simulation.

Extrait des logs :

```python
An error occurred unexpectedly while importing the study output: study.name='d1523bf8-0218-4184-a305-f7b16e0326d9', study.xpansion_mode=None, study.job_log_dir='/path/to/JOB_LOGS/d1523bf8-0218-4184-a305-f7b16e0326d9_15715', see stack trace below:
Traceback (most recent call last):
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 357, in _check_studies_state
    output_id = self._import_study_output(
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 278, in _import_study_output
    return self.callbacks.import_output(
  File "/antarest/launcher/service.py", line 561, in _import_output
    output_true_path = find_single_output_path(output_path)
  File "/antarest/study/storage/utils.py", line 124, in find_single_output_path
    children = os.listdir(all_output_path)
FileNotFoundError: [Errno 2] No such file or directory: '/slurm_workspace/tmpcrsrwwbg/OUTPUT/d1523bf8-0218-4184-a305-f7b16e0326d9/output'
```

## Comportement attendu

Avoir un message d'erreur qui indique un plantage de la simulation.

## Captures d'écran

N/A

## Solution possible

N/A

## Environnement

- ~Production~
- Staging

### Ajoutez ici tout autre contexte concernant le problème.

- ID d'étude : `3ff3ceef-796c-44bc-8744-c0f47edf99c6`
- ID de tâche : `d1523bf8-0218-4184-a305-f7b16e0326d9`

**Comment by laurent-laporte-pro** [comment]
Done in v2.13.1
