### ISSUE TITLE
matrix.error.failedToretrieveIndex error message

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1395]
## Description

Launch AntaresWeb 2.13 locally on Ubuntu 20.04. This is probably minor.

## Steps to Reproduce

1. Import a study from a zip archive
2. Create a variant from it
3. Navigate to an area, then to whatever time-series. For example thermal time-series for the area

## Actual Behavior
An error message was displayed in the web client (see screenshot below)

The logs for the app are
```
INFO:     127.0.0.1:45712 - "GET /v1/studies/712acc5c-cbe1-42bb-b973-84f8b68f7e07/matrixindex?path=input%2Fthermal%2Fprepro%2Fz_p2g_asservi%2Fz_p2g_asservi_global%2Fmodulation HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "anyio/streams/memory.py", line 94, in receive
  File "anyio/streams/memory.py", line 89, in receive_nowait
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette/middleware/base.py", line 41, in call_next
  File "anyio/streams/memory.py", line 114, in receive
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
  File "uvicorn/middleware/proxy_headers.py", line 75, in __call__
  File "fastapi/applications.py", line 212, in __call__
  File "starlette/applications.py", line 112, in __call__
  File "starlette/middleware/errors.py", line 181, in __call__
  File "starlette/middleware/errors.py", line 159, in __call__
  File "ratelimit/core.py", line 82, in __call__
  File "starlette/middleware/cors.py", line 84, in __call__
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/logging/utils.py", line 104, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/utils/fastapi_sqlalchemy/middleware.py", line 56, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/exceptions.py", line 82, in __call__
  File "starlette/exceptions.py", line 71, in __call__
  File "starlette/routing.py", line 656, in __call__
  File "starlette/routing.py", line 259, in handle
  File "starlette/routing.py", line 61, in app
  File "fastapi/routing.py", line 226, in app
  File "fastapi/routing.py", line 161, in run_endpoint_function
  File "starlette/concurrency.py", line 39, in run_in_threadpool
  File "anyio/to_thread.py", line 31, in run_sync
  File "anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio/_backends/_asyncio.py", line 867, in run
  File "antarest/study/web/studies_blueprint.py", line 289, in get_study_matrix_index
  File "antarest/study/service.py", line 801, in get_input_matrix_startdate
  File "antarest/study/storage/utils.py", line 290, in get_start_date
  File "_strptime.py", line 562, in _strptime_time
  File "_strptime.py", line 349, in _strptime
ValueError: time data 'july' does not match format '%B'
```

Describe what actually happened.
## Expected Behavior
No error message
Describe what you expected to happen.
## Screenshots
![image](https://user-images.githubusercontent.com/26088210/224315868-2c3e839b-0575-4ae9-b89d-2207669697a4.png)
![image](https://user-images.githubusercontent.com/26088210/224316838-85cdfc5e-b372-4fbb-af3d-40c17ee114cc.png)

## Possible Solution
This is not really a problem, just a scary error message. There seems to be no consequences: the time-series appear normally.

If you have a solution in mind, describe it here.
## Environment

- [ ] Production to be check
- [ ] Staging
- [X] Local install

### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to:
- Any relevant logs or error messages: see above
- Any relevant code snippets: ?
- Any relevant library versions: ?
- The date and time when the issue occurred: 10/03/2023
- Browser and version: Firefox 107.0
- Operating System: Ubuntu 20.04

**Comment by MartinBelthle** [comment]
I did not reproduce the bug and the error came from a part of the code that has changed with this PR : [fix(desktop): correct date parsing on localized environment](https://github.com/AntaresSimulatorTeam/AntaREST/pull/1568).
Therefore, i close this issue.
