### ISSUE TITLE
Intermittent Error 500 and Failed Matrix Modification

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1433]
## Description

The matrix sometimes isn't modified with an error message. Sometimes, the edit works (no error message, cell value modified), sometimes it doesn't (error message, call value not saved)

### Steps to reproduce the behavior:
1. Go to any timeseries
2. Click on a cell
3. Change its contents
4. Sometimes, an error 500 will appear. The matrix isn't modified after refreshing the page
## Actual Behavior

Describe what actually happened.
## Expected Behavior
The matrix is modified

Describe what you expected to happen.
## Screenshots
![image](https://user-images.githubusercontent.com/26088210/229124498-cd9ac00d-9221-4d5b-aa30-817ad65b6d85.png)

## Possible Solution

If you have a solution in mind, describe it here.
## Environment

- [X] Production
- [X] Staging
### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to:
- Any relevant logs or error messages: 
```
Status : 500
Exception :ValidationError
Description :Unexpected server error
```
- The date and time when the issue occurred: 31/03/2023
- AntaREST 2.12.3, ef61974f80fa6f627a2f074b178745479fb20347
- Browser and version: Firefox 107.0 (64 bits)
- Operating System: Ubuntu 20.04

**Comment by MartinBelthle** [comment]
@flomnes do you remember if this issue occured with a managed study or with a study on a disk ? If it happened on disk, it is probably because a study created with AntaresSimulator will have no matrix by default and AntaresWeb does not handle this case yet, see this feature request https://github.com/AntaresSimulatorTeam/AntaREST/issues/1529. I reproduced your issue with the case i described just above but I couldn't with a managed study.

**Comment by flomnes** [comment]
Sorry, I have no idea. Next time I'll make sure to include the study ID.

**Comment by laurent-laporte-pro** [comment]
This error is related to the denormalization:

```python
INFO:     127.0.0.1:33732 - "PUT /v1/studies/963b2999-85b2-4f60-8479-4a07ccaa52be/matrix?path=input/thermal/series/aa/b/series HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "anyio/streams/memory.py", line 98, in receive
  File "anyio/streams/memory.py", line 93, in receive_nowait
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette/middleware/base.py", line 41, in call_next
  File "anyio/streams/memory.py", line 118, in receive
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
  File "uvicorn/middleware/proxy_headers.py", line 75, in __call__
  File "fastapi/applications.py", line 212, in __call__
  File "starlette/applications.py", line 112, in __call__
  File "starlette/middleware/errors.py", line 181, in __call__
  File "starlette/middleware/errors.py", line 159, in __call__
  File "ratelimit/core.py", line 82, in __call__
  File "starlette/middleware/cors.py", line 92, in __call__
  File "starlette/middleware/cors.py", line 147, in simple_response
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/logging/utils.py", line 168, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/utils/fastapi_sqlalchemy/middleware.py", line 56, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/exceptions.py", line 82, in __call__
  File "starlette/exceptions.py", line 71, in __call__
  File "starlette/routing.py", line 656, in __call__
  File "starlette/routing.py", line 259, in handle
  File "starlette/routing.py", line 61, in app
  File "fastapi/routing.py", line 226, in app
  File "fastapi/routing.py", line 161, in run_endpoint_function
  File "starlette/concurrency.py", line 39, in run_in_threadpool
  File "anyio/to_thread.py", line 33, in run_sync
  File "anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio/_backends/_asyncio.py", line 807, in run
  File "antarest/study/web/study_data_blueprint.py", line 479, in edit_matrix
  File "antarest/study/service.py", line 2356, in update_matrix
  File "antarest/study/business/matrix_management.py", line 94, in update_matrix
  File "antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py", line 82, in denormalize
  File "pathlib.py", line 1325, in unlink
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: 'examples/studies/000 Free Data Sample/input/thermal/series/aa/b/series.txt.link'
```

**Comment by laurent-laporte-pro** [comment]
May be related to #1548
