### ISSUE TITLE
[ANT-703] HTTP 417 occurs when using R scripts

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1448]
## Description :

The R script creates a variant from a base study. It creates a new cluster for each area in the variant. Then, for each cluster, a TS matrix is added. It is this last operation that raises an HTTP 417 exception.
This behavior is random and therefore difficult to reproduce.

## How to reproduce : 

I couldn't reproduce it on my local server, but you can use the API to do the 3 operations described above and wait till the Exception occurs.

## Stack Trace : 

```python
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361,
  in _wrap_pool_connect return fn()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327,
  in connect return _ConnectionFairy._checkout(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894,
  in _checkout fairy = _ConnectionRecord.checkout(pool)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493,
  in checkout rec = pool._do_get()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146,
  in _do_get self._dec_overflow()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143,
  in _do_get return self._create_connection()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273,
  in _create_connection return _ConnectionRecord(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388,
  in __init__ self.__connect()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691,
  in __connect pool.logger.debug("Error on connect(): %s", e)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686,
  in __connect self.dbapi_connection = connection = pool._invoke_creator(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574,
  in connect return dialect.connect(*cargs, **cparams)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598,
  in connect return self.dbapi.connect(*cargs, **cparams)
File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122,
  in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  psycopg2.OperationalError: connection to server at "antares-prod-pg-db.rte-france.com" (10.133.8.140), port 65444 failed: FATAL: les emplacements de connexions restants sont réservés pour les connexions superutilisateur non relatif à la réplication

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 181,
  in _check_commands_validity self.command_factory.to_icommand(command)
File "/antarest/study/storage/variantstudy/command_factory.py", line 219,
  in to_icommand return [self._to_single_icommand(command_dto.action, args)]
File "/antarest/study/storage/variantstudy/command_factory.py", line 180,
  in _to_single_icommand return ReplaceMatrix(
File "/antarest/study/storage/variantstudy/model/command/replace_matrix.py", line 43,
  in __init__ super().__init__(
File "pydantic/main.py", line 339,
  in pydantic.main.BaseModel.__init__
File "pydantic/main.py", line 1056,
  in pydantic.main.validate_model
File "pydantic/fields.py", line 857,
  in pydantic.fields.ModelField.validate
File "pydantic/fields.py", line 1067,
  in pydantic.fields.ModelField._validate_singleton
File "pydantic/fields.py", line 871,
  in pydantic.fields.ModelField.validate
File "pydantic/fields.py", line 1121,
  in pydantic.fields.ModelField._apply_validators
File "pydantic/class_validators.py", line 315,
  in pydantic.class_validators._generic_validator_basic.lambda13
File "/antarest/study/storage/variantstudy/business/utils.py", line 18,
  in validate_matrix matrix_id = MATRIX_PROTOCOL_PREFIX + values[
File "/antarest/matrixstore/service.py", line 158,
  in create if not self.repo.get(matrix_hash):
File "/antarest/matrixstore/repository.py", line 98,
  in get matrix: Matrix = db.session.query(Matrix).get(id)
File "<string>", line 2,
  in get
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 468,
  in warned return fn(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 947,
  in get return self._get_impl(ident, loading.load_on_pk_identity)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 951,
  in _get_impl return self.session._get_impl(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2972,
  in _get_impl return db_load_fn(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530,
  in load_on_pk_identity session.execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1713,
  in execute conn = self._connection_for_bind(bind)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1552,
  in _connection_for_bind return self._transaction._connection_for_bind(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747,
  in _connection_for_bind conn = bind.connect()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3315,
  in connect return self._connection_cls(self, close_with_result=close_with_result)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96,
  in __init__ else engine.raw_connection()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3394,
  in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3364,
  in _wrap_pool_connect Connection._handle_dbapi_exception_noconnection(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2198,
  in _handle_dbapi_exception_noconnection util.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361,
  in _wrap_pool_connect return fn()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327,
  in connect return _ConnectionFairy._checkout(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894,
  in _checkout fairy = _ConnectionRecord.checkout(pool)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493,
  in checkout rec = pool._do_get()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146,
  in _do_get self._dec_overflow()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143,
  in _do_get return self._create_connection()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273,
  in _create_connection return _ConnectionRecord(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388,
  in __init__ self.__connect()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691,
  in __connect pool.logger.debug("Error on connect(): %s", e)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686,
  in __connect self.dbapi_connection = connection = pool._invoke_creator(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574,
  in connect return dialect.connect(*cargs, **cparams)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598,
  in connect return self.dbapi.connect(*cargs, **cparams)
File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122,
  in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "antares-prod-pg-db.rte-france.com" (10.133.8.140), port 65444 failed: FATAL: les emplacements de connexions restants sont réservés pour les connexions superutilisateur non relatif à la réplication (Background on this error at: https://sqlalche.me/e/14/e3q8) During handling of the above exception, another exception occurred: Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71,
  in __call__ await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656,
  in __call__ await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259,
  in handle await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61,
  in app response = await func(request)
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226,
  in app raw_response = await run_endpoint_function(
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161,
  in run_endpoint_function return await run_in_threadpool(dependant.call, **values)
File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 39,
  in run_in_threadpool return await anyio.to_thread.run_sync(func, *args)
File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31,
  in run_sync return await get_asynclib().run_sync_in_worker_thread(
File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937,
  in run_sync_in_worker_thread return await future
File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867,
  in run result = context.run(func, *args)
File "/antarest/study/web/variant_blueprint.py", line 193,
  in append_commands return study_service.apply_commands(sanitized_uuid, commands, params)
File "/antarest/study/service.py", line 1566,
  in apply_commands return self.storage_service.variant_study_service.append_commands(
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 238,
  in append_commands command_objs = self._check_commands_validity(study_id, commands)
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 187,
  in _check_commands_validity raise CommandNotValid( antarest.core.exceptions.CommandNotValid: Command at index 0 for study c9cde749-96d5-4676-b99c-52a2d12eebbb
```

**Comment by laurent-laporte-pro** [comment]
Le message d'erreur suivant est plutôt inquiétant :

```python
File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122,
  in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  psycopg2.OperationalError: connection to server at "antares-prod-pg-db.rte-france.com" (10.133.8.140), port 65444 failed: FATAL: les emplacements de connexions restants sont réservés pour les connexions superutilisateur non relatif à la réplication
```

Cela peut être causé par un dépassement de la limite de connexions autorisées ou par une mauvaise configuration du serveur PostgreSQL.

Pour connaître le nombre de connexions autorisées dans une base de données PostgreSQL, vous pouvez exécuter la requête SQL suivante en tant que superutilisateur ou en utilisant un rôle avec les privilèges nécessaires :

```sql

SELECT name, setting FROM pg_settings WHERE name = 'max_connections';
```

Cette requête renvoie le nombre maximal de connexions autorisées pour le cluster de base de données PostgreSQL, qui est défini par le paramètre "max_connections". **Le nombre par défaut de connexions autorisées est 100**, mais cela peut varier en fonction de la configuration du cluster de base de données.

**Comment by laurent-laporte-pro** [comment]
Autre cas d'erreur : timeout de connexion à la base de données :

```python
The above exception was the direct cause of the following exception: Traceback (most recent call last):
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 180,
  in _check_commands_validity self.command_factory.to_icommand(command) 
File "/antarest/study/storage/variantstudy/command_factory.py", line 219,
  in to_icommand return [self._to_single_icommand(command_dto.action, args)] 
File "/antarest/study/storage/variantstudy/command_factory.py", line 180,
  in _to_single_icommand return ReplaceMatrix( 
File "/antarest/study/storage/variantstudy/model/command/replace_matrix.py", line 43,
  in __init__ super().__init__( 
File "pydantic/main.py", line 339,
  in pydantic.main.BaseModel.__init__ 
File "pydantic/main.py", line 1056,
  in pydantic.main.validate_model 
File "pydantic/fields.py", line 857,
  in pydantic.fields.ModelField.validate 
File "pydantic/fields.py", line 1067,
  in pydantic.fields.ModelField._validate_singleton 
File "pydantic/fields.py", line 871,
  in pydantic.fields.ModelField.validate 
File "pydantic/fields.py", line 1121,
  in pydantic.fields.ModelField._apply_validators 
File "pydantic/class_validators.py", line 315,
  in pydantic.class_validators._generic_validator_basic.lambda13 
File "/antarest/study/storage/variantstudy/business/utils.py", line 18,
  in validate_matrix matrix_id = MATRIX_PROTOCOL_PREFIX + values[ 
File "/antarest/matrixstore/service.py", line 158,
  in create if not self.repo.get(matrix_hash): 
File "/antarest/matrixstore/repository.py", line 98,
  in get matrix: Matrix = db.session.query(Matrix).get(id) 
File "<string>", line 2,
  in get 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 468,
  in warned return fn(*args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 947,
  in get return self._get_impl(ident, loading.load_on_pk_identity) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 951,
  in _get_impl return self.session._get_impl( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2972,
  in _get_impl return db_load_fn( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530,
  in load_on_pk_identity session.execute( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1713,
  in execute conn = self._connection_for_bind(bind) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1552,
  in _connection_for_bind return self._transaction._connection_for_bind( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747,
  in _connection_for_bind conn = bind.connect() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3315,
  in connect return self._connection_cls(self, close_with_result=close_with_result) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96,
  in __init__ else engine.raw_connection() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3394,
  in raw_connection return self._wrap_pool_connect(self.pool.connect, _connection) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3364,
  in _wrap_pool_connect Connection._handle_dbapi_exception_noconnection( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2198,
  in _handle_dbapi_exception_noconnection util.raise_( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361,
  in _wrap_pool_connect return fn() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327,
  in connect return _ConnectionFairy._checkout(self) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894,
  in _checkout fairy = _ConnectionRecord.checkout(pool) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493,
  in checkout rec = pool._do_get() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146,
  in _do_get self._dec_overflow() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143,
  in _do_get return self._create_connection() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273,
  in _create_connection return _ConnectionRecord(self) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388,
  in __init__ self.__connect() 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691,
  in __connect pool.logger.debug("Error on connect(): %s", e) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70,
  in __exit__ compat.raise_( 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211,
  in raise_ raise exception 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686,
  in __connect self.dbapi_connection = connection = pool._invoke_creator(self) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574,
  in connect return dialect.connect(*cargs, **cparams) 
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598,
  in connect return self.dbapi.connect(*cargs, **cparams) 
File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122,
  in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "antares-opf-pg.applispfref.sipfref.local" (10.132.14.123), port 65443 failed: timeout expired (Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred: Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71,
  in __call__ await self.app(scope, receive, sender) 
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656,
  in __call__ await route.handle(scope, receive, send) 
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259,
  in handle await self.app(scope, receive, send) 
File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61,
  in app response = await func(request) 
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226,
  in app raw_response = await run_endpoint_function( 
File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159,
  in run_endpoint_function return await dependant.call(**values) 
File "/antarest/study/web/variant_blueprint.py", line 188,
  in append_commands return study_service.apply_commands(sanitized_uuid, commands, params) 
File "/antarest/study/service.py", line 1659,
  in apply_commands return self.storage_service.variant_study_service.append_commands( 
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 237,
  in append_commands command_objs = self._check_commands_validity(study_id, commands) 
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 186,
  in _check_commands_validity raise CommandNotValid(
antarest.core.exceptions.CommandNotValid: Command at index 0 for study 2fafff49-8c6f-4efd-8e9c-1000b6506f8a
```

**Comment by laurent-laporte-pro** [comment]
The use of a connections pool at SqlAlchemy level allows to solve most of the issues. We will open another ticket for the other problems, in particular the problem of long queries already identified.

**Comment by laurent-laporte-pro** [comment]
The use of a connections pool at SqlAlchemy level allows to solve most of the issues. We will open another ticket for the other problems, in particular the problem of long queries already identified.
