### ISSUE TITLE
Uncaught exceptions cause slurm launcher loop to stop

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1476]
## Description

Seen in production: 
the loop which monitors studies state in slurm launcher stops, because of an uncaught exception in `_handle_success`

Stack:
```
Traceback (most recent call last):
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 430, in _handle_success
    output_id = self._import_study_output(
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 280, in _import_study_output
    return self.callbacks.import_output(
...
```

This leaves the worker in an invalid state where the progress of all tasks is not monitored anymore.

## Expected Behavior

The monitoring loop must never stops, exceptions need to be handled "gracefully" in that thread.

## Environment

- [X] Production
- [ ] Staging

### Add any other context about the problem here.

For an example of such an error in  RTE prod env: see task 721a1167-a2c5-41c7-bed2-b26635ac658e on 17/04 at 21:33.

**Comment by sylvlecl** [comment]
Note that with the DB client timeout at 1h, this happens as soon as the study import lasts more than 1h, because of the long transaction that wraps it.
