### ISSUE TITLE
Standalone/desktop app can't be started

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1524]
## Description
```bash
omnesflo@gm0winl370:~/Téléchargements/AntaresWeb-ubuntu-2.14.0$ ./AntaresWeb/AntaresWebServer 
plyer/platforms/linux/notification.py:65: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
libpng warning: iCCP: CRC error
Process Process-1:
Traceback (most recent call last):
  File "logging/config.py", line 542, in configure
  File "logging/config.py", line 674, in configure_formatter
  File "logging/config.py", line 89, in _resolve
ModuleNotFoundError: No module named 'pythonjsonlogger'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "antarest/gui.py", line 21, in run_server
  File "antarest/main.py", line 185, in fastapi_app
  File "antarest/core/logging/utils.py", line 160, in configure_logger
  File "logging/config.py", line 808, in dictConfig
  File "logging/config.py", line 545, in configure
ValueError: Unable to configure formatter 'json'
^CTraceback (most recent call last):
  File "antarest/gui.py", line 95, in <module>
  File "antarest/gui.py", line 89, in main
KeyboardInterrupt
[112379] Failed to execute script 'gui' due to unhandled exception!
```

### Steps to reproduce the behavior:
1. Download https://github.com/AntaresSimulatorTeam/AntaREST/releases/download/v2.14.0/AntaresWeb-ubuntu-2.14.0.zip
2. Uncompress
3. Make the executable executable (chmod +x)
4. See error above

## Possible Solution
I tried to install pythonjsonlogger, but it doesn't fix the issue. Probably the environments are different.

Add [pythonjsonlogger](https://pypi.org/project/python-json-logger/) to `requirements.txt` ?

Looking at the diff since v2.13.0 (which was working), it seems that this bug is related to this PR "feat: standardize log messsage formats (#1431)"

```diff
@@ -41,11 +38,29 @@ def configure_logger(config: Config) -> None:
         "formatters": {
             "console": {
                 "class": "antarest.core.logging.utils.CustomDefaultFormatter",
-                "format": "%(asctime)s - %(trace_id)s - %(threadName)s - %(name)s - %(ip)s - %(user)s - %(pid)s - %(levelname)s - %(message)s",
+                "format": (
+                    "[%(asctime)s] [%(process)s] [%(name)s]"
+                    " - %(trace_id)s"
+                    " - %(threadName)s"
+                    " - %(ip)s"
+                    " - %(user)s"
+                    " - %(levelname)s"
+                    " - %(message)s"
+                ),
             },
             "json": {
-                "class": f"{JsonFormatter.__module__}.{JsonFormatter.__name__}",
-                "format": "%(asctime)s - %(trace_id)s - %(threadName)s - %(name)s - %(ip)s - %(user)s - %(pid)s - %(levelname)s - %(message)s",
+                "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
+                "format": (
```

## Environment

- [X] Production (desktop)
- [x] Staging
### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to:
- Any relevant logs or error messages: [e.g. console outputs, stack traces]

- The date and time when the issue occurred: 17/05/2023
- Browser and version: Firefox
- Operating System: Ubuntu 20.04

**Comment by laurent-laporte-pro** [comment]
We need to check everything works fine with the two fixes.

**Comment by laurent-laporte-pro** [comment]
Je confirme que l'application Antares Web v2.14.2 sous Ubuntu se lance correctement et l'application est bien servie.

Voici un extrait des logs :

```
$ ./AntaresWeb/AntaresWebServer
plyer/platforms/linux/notification.py:65: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
libpng warning: iCCP: CRC error
INFO:     Started server process [119179]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:40812 - "GET / HTTP/1.1" 200 OK
 ```
