### ISSUE TITLE
HTTP 500 Error on Modification of Empty Matrix in Thermal Cluster

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1571]
## Description

When creating a thermal cluster in Antares Web, the time series matrix appears empty (the file is empty), but a matrix
filled with zeros is displayed nonetheless. The problem arises when attempting to modify this matrix, resulting in an
error.

### Steps to reproduce the behavior:

1. Open a study
2. Click on "Modeling"
3. Select an area, and create a new thermal cluster
4. Open the newly created thermal cluster
5. Select the "Time Series" tab on the bottom to display the TS matrix
6. Try to change a cell

## Actual Behavior

An HTTP 500 is displayed

## Expected Behavior

The matrix should be updated.

## Screenshots

![empty_time_series_issue](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/04eda8aa-9af0-40b4-b1ce-f7195953999d)

## Possible Solution

Implement column insertion handling in this scenario to resolve the issue. This would allow for
seamless modification of the matrix without encountering any errors.

## Environment

- [x] Production
- [x] Staging
- [x] Development

### Add any other context about the problem here.

- Related to Antares Web v2.14.1
- Issue found with the "000 Free Data Sample" provided in the Antares Web Desktop version
- Requête PUT http://127.0.0.1:8080/v1/studies/963b2999-85b2-4f60-8479-4a07ccaa52be/matrix?path=input/thermal/series/aa/p/series with BODY = `[{"coordinates":[[6,0]],"operation":{"operation":"=","value":1571}}]`

**Comment by laurent-laporte-pro** [comment]
The solution is to avoid displaying a matrix with zeros when the matrix is actually empty. The user can import a matrix with the "Import" button. In the other hand, if the user uses the Swagger API, an error should be reported.

The HTTP status 422 Unprocessable Entity be suitable in this case. The 422 error code indicates that the request is well-formed, but the server cannot process it due to invalid parameters.

**Comment by laurent-laporte-pro** [comment]
Here is a possible stack trace:

```python
Traceback (most recent call last):
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/ratelimit/core.py", line 82, in __call__
    return await self.app(scope, receive, send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/laportelau/Projects/AntaREST/antarest/core/logging/utils.py", line 168, in dispatch
    response = await call_next(request)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/laportelau/Projects/AntaREST/antarest/core/utils/fastapi_sqlalchemy/middleware.py", line 56, in dispatch
    response = await call_next(request)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/laportelau/Projects/AntaREST/antarest/study/web/study_data_blueprint.py", line 479, in edit_matrix
    study_service.update_matrix(
  File "/home/laportelau/Projects/AntaREST/antarest/study/service.py", line 2360, in update_matrix
    self.matrix_manager.update_matrix(
  File "/home/laportelau/Projects/AntaREST/antarest/study/business/matrix_management.py", line 117, in update_matrix
    matrix_df: pd.DataFrame = matrix_node.parse(return_dataframe=True)
  File "/home/laportelau/Projects/AntaREST/antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py", line 84, in parse
    return pd.DataFrame(default) if return_dataframe else default
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 120, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/laportelau/Projects/AntaREST/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 674, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```
