### ISSUE TITLE
Cannot import / create a new study

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1607]
2.14.3, desktop version
Ubuntu 20.04

1. Start the desktop version
```bash
./AntaresWebServer -c ./resources/deploy/config.yaml
```
2. Open it in the browser
3. Try to import / create a study
4. Failure
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/26088210/1fece610-44f9-4884-8e01-1f233a78429f)
```
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: 'examples/internal_studies/4ba2e498-fd5a-41b5-a0c1-a474ab0688af'
INFO:     127.0.0.1:57022 - "POST /v1/studies?name=Exemple&version=850 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "anyio/streams/memory.py", line 98, in receive
  File "anyio/streams/memory.py", line 93, in receive_nowait
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette/middleware/base.py", line 41, in call_next
  File "anyio/streams/memory.py", line 118, in receive
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
  File "uvicorn/middleware/proxy_headers.py", line 75, in __call__
  File "fastapi/applications.py", line 212, in __call__
  File "starlette/applications.py", line 112, in __call__
  File "starlette/middleware/errors.py", line 181, in __call__
  File "starlette/middleware/errors.py", line 159, in __call__
  File "ratelimit/core.py", line 82, in __call__
  File "starlette/middleware/cors.py", line 92, in __call__
  File "starlette/middleware/cors.py", line 147, in simple_response
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/logging/utils.py", line 168, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/middleware/base.py", line 63, in __call__
  File "antarest/core/utils/fastapi_sqlalchemy/middleware.py", line 56, in dispatch
  File "starlette/middleware/base.py", line 44, in call_next
  File "starlette/middleware/base.py", line 34, in coro
  File "starlette/exceptions.py", line 82, in __call__
  File "starlette/exceptions.py", line 71, in __call__
  File "starlette/routing.py", line 656, in __call__
  File "starlette/routing.py", line 259, in handle
  File "starlette/routing.py", line 61, in app
  File "fastapi/routing.py", line 226, in app
  File "fastapi/routing.py", line 161, in run_endpoint_function
  File "starlette/concurrency.py", line 39, in run_in_threadpool
  File "anyio/to_thread.py", line 33, in run_sync
  File "anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio/_backends/_asyncio.py", line 807, in run
  File "antarest/study/web/studies_blueprint.py", line 248, in create_study
  File "antarest/study/service.py", line 766, in create_study
  File "antarest/study/storage/rawstudy/raw_study_service.py", line 223, in create
  File "pathlib.py", line 1288, in mkdir
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: 'examples/internal_studies/6780d72f-d136-4be8-8ed9-5ae5f2964dec'
```

**Comment by flomnes** [comment]
As discussed with @MartinBelthle, it's necessary to start AntaresWebWorker from the parent directory. Then everything works.
