### ISSUE TITLE
[ANT-871] Timeout error when updating variant properties or matrices with API

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1780]
## Description

When the user uses the API to update study variants and the variants have a large number of ancestors, we sometimes get a timeout error that crashes processing.

Updates concern both properties and matrices: for example, we have a study with thermal clusters whose parameters are varied with each variant.

The accumulation of timeouts leads to an overload in the number of connections made to the database, gradually bringing the Antares Web server to a standstill. This eventually requires a restart.

## Screenshots

Database connection issue:

![MicrosoftTeams-image (1)](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/2de9f5f8-0122-46cc-8d81-2ad3f8958577)

## Additional Information

Related stack trace found in the logs:

```Python
Traceback (most recent call last):
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 972, in
  _safe_generation if not self.exists(metadata) and not self._wait_for_generation(metadata, timeout):
File "/antarest/study/storage/variantstudy/variant_study_service.py", line 966, in
  _wait_for_generation self.task_service.await_task(task_id, timeout)
File "/antarest/core/tasks/service.py", line 289, in await_task
  self.tasks[task_id].result(timeout_sec or DEFAULT_AWAIT_MAX_TIMEOUT)
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
  raise TimeoutError() concurrent.futures._base.TimeoutError
```

**Comment by laurent-laporte-pro** [comment]
## Analysis

When a user requests the properties or matrices of a variant from a study on Antares Web, the system must first create an instant copy (snapshot) of that study on the disk. Creating this copy involves recursively retrieving the properties and matrices of all parent versions of the variant, and then merging them with the properties and matrices of the variant itself.

The current process relies on the use of asynchronous tasks. Each copy creation is managed in a task that follows the following scheme:
- For each variant to be copied, a creation task is launched. This task starts by retrieving the parameters of the parent study, which triggers a new creation task recursively until the base study.
- When the variant creation task has retrieved all parameters from its parent versions, it merges them and saves them to the disk.
- The generation of TSV files for the matrices (de-normalization) occurs at the end of the copy creation process and not during the creation of each variant.

From an implementation perspective, task management is handled by a `ThreadPoolExecutor` at the `TaskJobService` level, which controls a set of threads. This pool is configured to support a maximum of 15 concurrent tasks in production. This information is found in the application configuration file `application.yaml`: `max_workers: 15`.

This approach leads to nested asynchronous tasks, which creates a problem: each task occupies a slot in the pool and waits for its child tasks to finish before completing. When there is a large number of variants, the first task waits for all the others (due to the recursive call), but as there are only 15 slots, the last child tasks cannot start because they have to wait for a slot to become available. Consequently, the first task reaches the 60-second timeout, the copy process fails, and the other tasks remain in progress.

A second issue concerns connections to the database: each task opens a connection, but because orphaned tasks remain ongoing, the connections do not close, and their accumulation leads to reaching the maximum allowed connections, causing database connection errors.
